backend:
  name: github
  repo: GameDev-fyi/gamedev-fyi
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "countries"
    label: "Countries"
    folder: "content/countries"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Site Link", name: "site_link", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}